### ISSUE TITLE
Nivo Slider isn't pickup up proper content object

### ISSUE THREAD

**Issue by Tigerlady** [stevewithington/MuraNivo#5] opened 2015-08-02 15:42 UTC
Steve,  I updated a dev site core and site to the latest build.  Afterwards one of the Nivo Sliders that I use on the home page it isn't picking up the content collection that i want it to use.  In fact it looks like it is picking up just random feeds off the site. When i look at the source code it looks like a random id that it is using. 

Here is what is showing in the code.  
jQuery(document).ready(function($) {
$('#0f4597a6455243908d446974d7f2449b').nivoSlider({
effect: 'random',
pauseTime: 3000

Here is what i have the settings set for.

![image](https://cloud.githubusercontent.com/assets/1850313/9026808/0e3d4222-3903-11e5-9507-6f0e3a96a43c.png)

I was on version  6235  and upgraded to 6341.  I do not find any js errors in the console I am a bit lost as to what to look for.

**Comment by Tigerlady** [comment] 2015-08-02 19:03
One more thing.  I have been trying to trouble shoot this in the mean time so tried setting up the same feeds on another site.  The basically Nivo is showing all the images from all the feeds even if it hasn't been assigned to the content.  So even though I am specifying to use the HomeCarousel as the local content Index as soon as I added another local content index those images are also being displayed.

**Comment by Tigerlady** [comment] 2015-08-04 16:06
Steve,  I still do not know why this is happening but i have upgraded another site to the latest build of Mura and then did some testing.  So here are the conclusions.  

I added a page called slideshow test to mura.   Then I zoomed in to the page did a quick upload of a couple of images.   I didn't modify any of the images at that point just uploaded them.  When I refresh the home page which has the Nivo Slider the new images are displaying in the slider even though they are not part of the Local Index that is set to be displayed in the slider.  Basically from what i can tell all images that are uploaded through the quick upload or selected as a file when uploaded are being pulled by the slider.

**Comment by stevewithington** [comment] 2015-08-06 21:53
@Tigerlady I can't reproduce your issue. However, I suggest removing the display object completely, and then try reassigning it, select your desired content collection and publish again.

The only thing I can think of is that maybe the original content collection that was being used got deleted. I'll take a look at adding some code that addresses this issue if it should happen.

Thanks!

**Comment by stevewithington** [comment] 2015-08-06 22:05
@Tigerlady I just ran a few more tests and confirmed that the only way to see your result is if someone deleted the original content collection that was being used for the slider. That said, I've added some code to display an error message now if this happens. So, if you update your plugin with the latest version, you should see the error message. Thanks!

**Closed by stevewithington** 2015-08-06 22:05 UTC
Labels: unable to reproduce
